### ISSUE TITLE
Evitare il passaggio di `MEETUP_JSON`

### ISSUE THREAD

**Issue by cstrap** [PythonMilano/pyGlialo#13]
È un globalne e pure mutabile... 

Potrebbe esser interessante coprire di test unitari il progetto... magari in una serata di un prossimo meetup.

Vediamo :)

**Comment by zanza00** [comment]
Lo so che è brutto ma mi serviva una cosa veloce per avere qualcosa di funzionante... e come tutte le cose temporanee è rimasta :\
