### ISSUE TITLE
Migrare le API di meetup alla v3

### ISSUE THREAD

**Issue by zanza00** [PythonMilano/pyGlialo#33]
Bisogna migrare alle API di meetup [versione 3](https://www.meetup.com/meetup_api/docs/:urlname/events/:id/#get)

**Comment by cstrap** [comment]
Le api non sono cambiate, probabilmente non avendo inserito una data di fine, la response risultava vuota.
Ho aggiunto il fallback per pescare i vecchi meetup dove viene preso l'ultimo in ordine temporale.

**Comment by cstrap** [comment]
RIP Meetup.
